# -*- coding: utf-8 -*-
"""asau0735_DATA1002_Part2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IWUaUmT9fXaASHSJ__mCwEVgGToBKXWq
"""

import pandas as pd  # import panda functions
import numpy as np  # import statistic and math functions
import matplotlib as plt

data = pd.read_csv('SDG_goal3_clean (1).csv')  # import csv data into a Panda Data Frame
data.info()

data.isna().sum()  # Check if there are any Nans in each column
data.isnull().sum()  # Check if there are any blank spaces in each column

df = data[["Country",	"Year",	"Region", "Mortality rate attributed to cardiovascular disease, cancer, diabetes or chronic respiratory disease (probability):::BOTHSEX", "Fraction of deaths due to diabetes, among deaths due to cardiovascular disease, cancer, diabetes or chronic respiratory disease", "Fraction of deaths due to cancer, among deaths due to cardiovascular disease, cancer, diabetes or chronic respiratory disease"]]
#UD.rename(columns={"Mortality rate attributed to cardiovascular disease, cancer, diabetes or chronic respiratory disease (probability):::BOTHSEX": "Probability", "Fraction of deaths due to diabetes, among deaths due to cardiovascular disease, cancer, diabetes or chronic respiratory disease": "Fraction D", "Fraction of deaths due to cancer, among deaths due to cardiovascular disease, cancer, diabetes or chronic respiratory disease": "Fraction C"}, inplace=True)
#UD["Region"].unique()
df = df.rename(columns={"Mortality rate attributed to cardiovascular disease, cancer, diabetes or chronic respiratory disease (probability):::BOTHSEX": "Mortality rate attributed to cardiovascular disease, cancer, diabetes or chronic respiratory disease (probability)"})
df.info()

UD = df.to_dict('records')
UD
gas = {}  # Group Aggregate Summary
for row in UD:
  if row["Region"] not in gas:
    gas[row["Region"]] = {"Mor": [], "FD": [], "FC": []}
  gas[row["Region"]]["Mor"].append(row["Mortality rate attributed to cardiovascular disease, cancer, diabetes or chronic respiratory disease (probability)"])
  gas[row["Region"]]["FD"].append(row["Fraction of deaths due to diabetes, among deaths due to cardiovascular disease, cancer, diabetes or chronic respiratory disease"])
  gas[row["Region"]]["FC"].append(row["Fraction of deaths due to cancer, among deaths due to cardiovascular disease, cancer, diabetes or chronic respiratory disease"])

nc = {"Region" : list(gas),"median mortality rate attributed to cardiovascular disease, cancer, diabetes or chronic respiratory disease": [], "mean mortality rate attributed to cardiovascular disease, cancer, diabetes or chronic respiratory disease": [], "sd mortality rate attributed to cardiovascular disease, cancer, diabetes or chronic respiratory disease": [], "max mortality rate attributed to cardiovascular disease, cancer, diabetes or chronic respiratory disease": [], "min mortality rate attributed to cardiovascular disease, cancer, diabetes or chronic respiratory disease": [], "median fraction of deaths due to diabetes, among deaths due to cardiovascular disease, cancer, diabetes or chronic respiratory disease": [], "mean fraction of deaths due to diabetes, among deaths due to cardiovascular disease, cancer, diabetes or chronic respiratory disease": [], "sd fraction of deaths due to diabetes, among deaths due to cardiovascular disease, cancer, diabetes or chronic respiratory disease": [], "max fraction of deaths due to diabetes, among deaths due to cardiovascular disease, cancer, diabetes or chronic respiratory disease": [], "min fraction of deaths due to diabetes, among deaths due to cardiovascular disease, cancer, diabetes or chronic respiratory disease": [], "median fraction of deaths due to cancer, among deaths due to cardiovascular disease, cancer, diabetes or chronic respiratory disease": [], "mean fraction of deaths due to cancer, among deaths due to cardiovascular disease, cancer, diabetes or chronic respiratory disease": [], "sd fraction of deaths due to cancer, among deaths due to cardiovascular disease, cancer, diabetes or chronic respiratory disease": [], "max fraction of deaths due to cancer, among deaths due to cardiovascular disease, cancer, diabetes or chronic respiratory disease": [], "min fraction of deaths due to cancer, among deaths due to cardiovascular disease, cancer, diabetes or chronic respiratory disease": []}
for reg in gas:
  nc["median mortality rate attributed to cardiovascular disease, cancer, diabetes or chronic respiratory disease"].append(np.median(gas[reg]["Mor"]))
  nc["mean mortality rate attributed to cardiovascular disease, cancer, diabetes or chronic respiratory disease"].append(np.mean(gas[reg]["Mor"]))
  nc["sd mortality rate attributed to cardiovascular disease, cancer, diabetes or chronic respiratory disease"].append(np.std(gas[reg]["Mor"]))
  nc["max mortality rate attributed to cardiovascular disease, cancer, diabetes or chronic respiratory disease"].append(max(gas[reg]["Mor"]))
  nc["min mortality rate attributed to cardiovascular disease, cancer, diabetes or chronic respiratory disease"].append(min(gas[reg]["Mor"]))

  nc["median fraction of deaths due to diabetes, among deaths due to cardiovascular disease, cancer, diabetes or chronic respiratory disease"].append(np.median(gas[reg]["FD"]))
  nc["mean fraction of deaths due to diabetes, among deaths due to cardiovascular disease, cancer, diabetes or chronic respiratory disease"].append(np.mean(gas[reg]["FD"]))
  nc["sd fraction of deaths due to diabetes, among deaths due to cardiovascular disease, cancer, diabetes or chronic respiratory disease"].append(np.std(gas[reg]["FD"]))
  nc["max fraction of deaths due to diabetes, among deaths due to cardiovascular disease, cancer, diabetes or chronic respiratory disease"].append(max(gas[reg]["FD"]))
  nc["min fraction of deaths due to diabetes, among deaths due to cardiovascular disease, cancer, diabetes or chronic respiratory disease"].append(min(gas[reg]["FD"]))
  
  nc["median fraction of deaths due to cancer, among deaths due to cardiovascular disease, cancer, diabetes or chronic respiratory disease"].append(np.median(gas[reg]["FC"]))
  nc["mean fraction of deaths due to cancer, among deaths due to cardiovascular disease, cancer, diabetes or chronic respiratory disease"].append(np.mean(gas[reg]["FC"]))
  nc["sd fraction of deaths due to cancer, among deaths due to cardiovascular disease, cancer, diabetes or chronic respiratory disease"].append(np.std(gas[reg]["FC"]))
  nc["max fraction of deaths due to cancer, among deaths due to cardiovascular disease, cancer, diabetes or chronic respiratory disease"].append(max(gas[reg]["FC"]))
  nc["min fraction of deaths due to cancer, among deaths due to cardiovascular disease, cancer, diabetes or chronic respiratory disease"].append(min(gas[reg]["FC"]))
ndf = pd.DataFrame(nc)
ndf